#CREATE TABLE IF NOT EXISTS `xserver` (
#  `ID` int(11) NOT NULL AUTO_INCREMENT,
#  `NAME` varchar(64) COLLATE utf8_bin NOT NULL,
#  `ADRESS` varchar(128) COLLATE utf8_bin NOT NULL,
#  `PW` varchar(20) COLLATE utf8_bin NOT NULL,
#  PRIMARY KEY (`ID`),
#  UNIQUE KEY `ID` (`ID`),
#  UNIQUE KEY `ADRESS` (`ADRESS`),
#  KEY `ID_2` (`ID`)
#) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=33 ;

useMotdForServername: false
servername: 'proxy'

mysql:
   User: user
   Pass: pass
   Data: database
   Host: host
   Port: port
   Table: xserver