name: XServer
main: de.mickare.xserver.BukkitXServerPlugin
version: 2.0.5
author: mickare
description: XServer Communication Interface, that plugins can use to send messages to other servers.
commands:
  xserver:
    description: Main Command, has various subcommands (/xserver help for more).
    usage: /<command>
    permission: xserver
    permission-message: You don't have <permission>